### ISSUE TITLE
Can't use "python3 manage.py runserver"

### ISSUE THREAD

**Issue by Ashley2201** [fabian-hk/nano_siem#6]
I typed that command but i received a error: "TypeError: can only concatenate str (not "NoneType") to str". Can you fix it, please?

**Comment by fabian-hk** [comment]
Thank you for your interest in my project. I just ran the command, and it works for me. Can you share more about what you are trying to do? Do you want to develop new features, or do you want to use it? If you just want to use it, I would strongly recommend you use the prebuilt Docker container from Docker Hub.

**Comment by fabian-hk** [comment]
If you want to see how the software looks and what it does, you can start the demo in [doc/demo](https://github.com/fabian-hk/nano_siem/tree/main/doc/demo). Note that the Overwatch site does currently not work.

**Comment by 4zum4** [comment]
Sorry about late answer, but my problem was solved. Thank you for your reply. Have a good day!

**Comment by 4zum4** [comment]
Closed
